<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AWSSDK.Lambda" Version="4.0.15.6" />
		<PackageReference Include="AWSSDK.EventBridge" Version="4.0.6" />
		<PackageReference Include="AWSSDK.IdentityManagement" Version="4.0.9.26" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AwsDoc4.Resources\AwsDoc4.Resources.csproj" />
	</ItemGroup>

</Project>
